### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by hamada456** [hamada456/furima-31719#11]
自身のフリマアプリのURL
https://furima-31719.herokuapp.com/
Basic認証のIDとパスワード
ID：admin　パスワード：2222
出品者用のメールアドレスとパスワード
makonari@gmail.com　パスワード：aaaaa1
購入者用のメールアドレスとパスワード
makonari2@gmail.com　パスワード：aaaaa1
購入用カードの番号・期限・セキュリティコード
番号：4242424242424242
期限：3/33
CVC：123

**Comment by hamada456** [comment]
完成しました、よろしくお願いします。

**Comment by naokihayasan127** [comment]
濱田さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！
[修正箇所]

・ログイン状態では、ヘッダーにユーザーのニックネーム/ログアウトボタンが表示されること
こちら、ユーザーネームのみ表示されるようにしましょう！
「ようこそ！」は素敵ですが、今回は消しておきましょう！

修正し次第、以下の最終課題完了報告フォームを再度提出お願いします！
※新しいissueを作っていただく必要はありません
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by hamada456** [comment]
挙動確認ありがとうございます、修正しましたのでよろしくお願いします。

**Comment by naokihayasan127** [comment]
ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます:クラッカー:
おめでとうございます！

確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。
